# fly.toml app configuration file generated for dev-circle on 2024-01-02T13:44:16-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dev-circle"
primary_region = "ewr"

[experimental]
  cmd = ["npm", "run", "flyio-start"]
  auto_rollback = true

[build.args]
  NODE_ENV="production"
  PORT="5000"

[env]
  HOSTNAME="0.0.0.0"
  PORT="5000"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
